### ISSUE TITLE
update

### ISSUE THREAD

**Issue by pradzgaming** [Valentin-alix/Bot-Dofus-Mitm#2]
Salut plus moyen de se co en jeu avec le tool depuis l'update du 06/02 normal ?

**Comment by Valentin-alix** [comment]
Salut j'ai pas retester depuis, peux être que tu n'as pas lancer le script/init.sh, il faut relancer ce script à chaque maj

**Comment by pradzgaming** [comment]
Salut pourtant c’est la première chose que j’ai effectué, j’ai vu sur la cmd que lip de co pour rentrer en jeu avant changer, peut être un paquet bloquer quelque part ici ?
